[package]
name = "warcio"
version = "0.1.0"
authors = ["Peter Marheine <peter@taricorp.net>"]
edition = "2018"

description = "A library for reading and writing WARC files"
repository = "https://gitlab.com/taricorp/warcdedupe"
readme = "README.md"
license = "BSD-3-Clause"

categories = ["science"]
keywords = ["warc", "revisit", "deduplicate"]

[dependencies]
chrono = { version = "0.4.0", optional = true }
lazy_static = "1.0.0"
log = "0.4.1"
regex = "1.5.4"
twoway = "0.2.2"
