language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
script:
  - |
      cargo build --verbose &&
      cargo test --verbose &&
      cargo build --no-default-features &&
      cargo test --no-default-features
